name: Bug Report
description: Report a bug or an issue in the game.
labels: "bug"
title: "Bug Report: "
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: I have properly named the issue
        - label: I have checked the issues/discussions pages to see if the issue has been previously reported

  - type: dropdown
    attributes:
      label: What platform are you using?
      options:
        - Scratch (Web)
    validations:
      required: true

  #type: dropdown
    #attributes:
      #label: If you are playing on a browser, which one are you using?
      #options:
        #- Google Chrome
        #- Microsoft Edge
        #- Firefox
        #- Opera
        #- Safari
        #- Other (Specify below)

  - type: input
    attributes:
      label: Version
      description: What version are you using?
      placeholder: ex. 0.1.5
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Describe your bug."

  - type: markdown
    attributes:
      value: "### Please do not report issues from other versions and or forks. These must be reported in their respective repositories."

  - type: markdown
    attributes:
      value: "#### Provide as many details as you can."

  - type: textarea
    attributes:
      label: Context (Provide images, videos, etc.)

  - type: textarea
    attributes:
      label: Steps to reproduce (or crash logs, errors, etc.)
